// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc810.HBot;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;


/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveMiddleWheel;
    public static SpeedController driveFrontLeft;
    public static SpeedController driveFrontRight;
    public static SpeedController driveBackLeft;
    public static SpeedController driveBackRight;
    public static RobotDrive driveRobotDrive;
    public static Compressor pneumaticsCompressor;
    public static Solenoid pneumaticsMiddleWheelToggle;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveMiddleWheel = new Victor(4);
        LiveWindow.addActuator("Drive", "MiddleWheel", (Victor) driveMiddleWheel);
        
        driveFrontLeft = new Victor(0);
        LiveWindow.addActuator("Drive", "FrontLeft", (Victor) driveFrontLeft);
        
        driveFrontRight = new Victor(1);
        LiveWindow.addActuator("Drive", "FrontRight", (Victor) driveFrontRight);
        
        driveBackLeft = new Victor(2);
        LiveWindow.addActuator("Drive", "BackLeft", (Victor) driveBackLeft);
        
        driveBackRight = new Victor(3);
        LiveWindow.addActuator("Drive", "BackRight", (Victor) driveBackRight);
        
        driveRobotDrive = new RobotDrive(driveFrontLeft, driveBackLeft,
              driveFrontRight, driveBackRight);
        
        driveRobotDrive.setSafetyEnabled(true);
        driveRobotDrive.setExpiration(0.1);
        driveRobotDrive.setSensitivity(0.5);
        driveRobotDrive.setMaxOutput(1.0);

        pneumaticsCompressor = new Compressor(0);
        
        
        pneumaticsMiddleWheelToggle = new Solenoid(0, 0);
        LiveWindow.addActuator("Pneumatics", "MiddleWheelToggle", pneumaticsMiddleWheelToggle);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        

        ((SafePWM) driveMiddleWheel).setSafetyEnabled(true);
    }
}
